FROM python:3.12-alpine

WORKDIR /app

COPY requirements.txt .

RUN pip install setuptools && pip install --no-cache-dir -r requirements.txt && pip install psycopg2-binary

ENV PYTHONPATH=/app

COPY . .

RUN python manage.py collectstatic --noinput
EXPOSE 8000

CMD [ "python3", "manage.py", "runserver", "0.0.0.0:8000" ]