events {
    worker_connections 1024;
}

http {
    upstream backend {
        server backend:8000;
    }

    upstream frontend {
        server frontend:3000;
    }

    server {
        listen 80;
        server_tokens off;
        client_max_body_size 20M;

        location /api/ {
            proxy_set_header Host $http_host;
            proxy_pass http://backend;
        }

        location /admin/ {
            proxy_set_header Host $http_host;
            proxy_pass http://backend;
        }

        location /static/admin/ {
            alias /static/admin/;
            expires 1y;
            add_header Cache-Control "public";
            access_log off;

            types {
                text/css css;
                application/javascript js;
                image/svg+xml svg;
                image/png png;
                image/jpeg jpg jpeg;
                image/x-icon ico;
                font/woff2 woff2;
                font/woff woff;
                font/ttf ttf;
            }

            location ~ \.css$ {
                add_header Content-Type text/css;
            }
    
            location ~ \.js$ {
                add_header Content-Type application/javascript;
            }
        }

        location /static/rest_framework/ {
            alias /static/rest_framework/;
            expires 1y;
            add_header Cache-Control "public";
            access_log off;
        }

        location /static/ {
            alias /static/;
            expires 1y;
            add_header Cache-Control "public";
            access_log off;
            try_files $uri @frontend_static;
        }

        location @frontend_static {
            proxy_pass http://frontend;
        }

        location /media/ {
            alias /media/;
            expires 30d;
            add_header Cache-Control "public";
            access_log off;
        }

        location / {
            proxy_set_header Host $http_host;
            proxy_pass http://frontend;
        }
    }
}
